### ISSUE TITLE
Table 'craft_cache' doesn't exist

### ISSUE THREAD

**Issue by admench** [nystudio107/craft-scripts#15]
Thanks for a great set of scripts Andrew.

I am having this issue:

```
Removing cache dir /home/forge/www.domainname.co.uk/craft/storage/runtime/cache
Removing cache dir /home/forge/www.domainname.co.uk/craft/storage/runtime/compiled_templates
Removing cache dir /home/forge/www.domainname.co.uk/craft/storage/runtime/state
Emptying cache table craft_cache
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1146 (42S02) at line 1: Table 'craft.domainname.craft_cache' doesn't exist
Emptying cache table craft_templatecaches
mysql: [Warning] Using a password on the command line interface can be insecure.
*** Caches cleared
```

Could it be because the database name `craft.domainname` has a dot in it?

The `craft_templatecaches` table empties without issue.

**Comment by khalwat** [comment]
Yes, this isn't an issue at all. It's normal for that table not to exist, unless you have Craft set up to cache things in the database (the default is a file cache). In Craft-Scripts 1.2.2 I have it not outputting errors for this very reason.
