### ISSUE TITLE
FR: Ability to use a remote .env.sh's LOCAL values as REMOTE

### ISSUE THREAD

**Issue by johndwells** [nystudio107/craft-scripts#17]
When setting up a local `.env.sh` file, which pulls from a remote source, we have to repeat a lot of values (paths, DB creds, etc) that are (potentially) already set in that remote server's own `.env.sh` file. So it would be great if we could simply define:

REMOTE_ENV_PATH

And if `REMOTE_ENV_PATH` is defined, then the scripts uses the `LOCAL_` values found in that `.env.sh` file as the `REMOTE_` values at runtime.

**Comment by khalwat** [comment]
mmmmm... that'd require ssh'ing in to pull that file down. I'll have to consider the implications of that... but I hear what you're saying.

I guess I look at it from the POV that the setup only happens once, so it's not a big deal if there's some repetition involved.

**Comment by khalwat** [comment]
Thought about it, but for transparency reasons, I'm gonna leave it as is. Feel free to fork it if you like.

**Comment by johndwells** [comment]
Given my lack of shell skills, I'll probably leave it too. But I still think it's a good idea. :)
