### ISSUE TITLE
FR: clear assettransformindex as part of clear_caches.sh

### ISSUE THREAD

**Issue by johndwells** [nystudio107/craft-scripts#18]
We have opted to use `.rsync-filter` to exclude asset transforms when doing any environment synching / backup (to save on storage, bandwidth).  But as a result, any time we do a remote -> local sync for continuous development, we always have to jump into Craft's CP to manually clear the Asset Transform Index cache.  So if the clear_caches.sh script could also include the `craft_assettransformindex` table, that would really help!

**Comment by khalwat** [comment]
That is a good idea; though we probably wouldn't want to clear it every time in most installations.

What I'd suggest doing is go ahead and modify the `CRAFT_CACHE_TABLES` constant in your copy of `clear_caches.sh` to add whatever tables you want cleared. Potentially it could be moved out to a config variable, but I'm not sure how common of a use-case this would be.

https://github.com/nystudio107/craft-scripts/blob/master/scripts/clear_caches.sh#L51
