### ISSUE TITLE
Syncing assets subdirectories

### ISSUE THREAD

**Issue by tobystokes** [nystudio107/craft-scripts#24]
Thanks for these scripts (and every blog post about Craft!)

I think there is an issue syncing assets that are in subdirectories of the base path, for instance, if env:
```
LOCAL_ASSETS_PATH=${LOCAL_ROOT_PATH}"public/assets/"
LOCAL_ASSETS_DIRS=(
                "images/products/subfolder1"
                "pdfs/brochures"
                )
```
Then the pulled assets will end up at 
```
[...]public/assets/subfolder1
[...]public/assets/brochures
```
(missing out the extra path bit)

I think it's fixable using 
https://github.com/tobystokes/craft-scripts/commit/26309c72ee7100a85c1bf98e0e3702ffdbb3b06a
(adds the DIR path, but deletes shortest match after the last "/" which in the case on no subdirectory, is everything)
Works For Me, not rigorously tested, could be cleaned up for PR, but maybe I'm missing a trick in my setup?

**Comment by khalwat** [comment]
So there shouldn't be an issue with this, assuming you have your local and remote paths matched properly. Are you sure you do?

**Comment by tobystokes** [comment]
I think my paths are correct and matched, but if no-one else has this trouble, feel free to ignore.

**Comment by jmauzyk** [comment]
I'm running into this issue as well. Can you provide pointers on how to get this working with subdirectories?
