### ISSUE TITLE
Restore Assets

### ISSUE THREAD

**Issue by samuelbirch** [nystudio107/craft-scripts#25]
as well as restore_db.sh, a restore_assets.sh option would be useful too.

**Comment by ademers** [comment]
And also `restore_dirs.sh`. Would this make sense?

**Comment by khalwat** [comment]
It might make sense... you'd want it to restore them from the default backup directories?

**Comment by khalwat** [comment]
Thanks for the PR @samuelbirch -- I ended up rolling it into the 1.2.6 release:
