### ISSUE TITLE
pull_db issue

### ISSUE THREAD

**Issue by mobiusint** [nystudio107/craft-scripts#27]
I successfully have been able to download the assets and I used to be able to download the database from the server, but now I am getting an error once the db says it was imported.

Craft Error: Craft appears to be installed but the info table is empty.
Command Line Errors: ERROR 1235 (42000) at line 3830: This version of MySQL doesn't yet support 'multiple triggers with the same action time and event for one table'

**Comment by khalwat** [comment]
So I'm pretty certain this isn't an issue with Craft-Scripts -- what version of MySQL are you running locally?

**Comment by mobiusint** [comment]
Hey there,

Thanks for the reply!  This is what I have on my system here. OS X
Server version: 5.5.5-10.2.12-MariaDB Homebrew


---
Josh Beers

**Comment by khalwat** [comment]
Not sure what is going on, or why (and I'm pretty sure it's unrelated to Craft-Scripts) but perhaps this helps:

http://www.lemiffe.com/5-solutions-for-mysql-error-1235/

**Comment by mobiusint** [comment]
Yes it’s strange. I even use the script on the same server without ssh and it gives me this:

./pull_db.sh
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
*** Backed up local database to /tmp/snc_craftcms_staging-db-backup-20180119.sql.gz
Warning: Using a password on the command line interface can be insecure.
ERROR 1235 (42000) at line 3830: This version of MySQL doesn't yet support 'multiple triggers with the same action time and event for one table'
*** Restored local database from /tmp/snc_site-db-dump-20180119.sql.gz

When I load the site it then shows me the attached.



---
Josh Beers

**Comment by khalwat** [comment]
If you meant to attach something, I'm not seeing it?

**Comment by mobiusint** [comment]
Sorry it’s Mac email so I think it’s just putting it inline
Here it is. It’s saying the craft info table is empty…so looks like it imports it, but info table is empty?


---
Josh Beers

**Comment by khalwat** [comment]
All that the scripts do is dump the database, excluding certain cache tables, via `mysqldump`

While it's possible there's something wrong with the scripts, I use them every day, and haven't run into an issue like this. It sounds/seems like something is funky either with the database, or your local or remote setup.

¯\_(ツ)_/¯

**Comment by mobiusint** [comment]
Ok cool! Thanks for the feedback. It’s truly weird.
I will message back if I figure it out. :)
Awesome scripts!
Need to find one like this for Wordpress now lol


---
Josh Beers

**Comment by khalwat** [comment]
The scripts actually very likely could work with WordPress, too. As far as they are concerned, it's just a db somewhere, and some files somewhere.
