### ISSUE TITLE
sync_backups_to_s3 needs PATH with Laravel Forge scheduler (doc suggestion)

### ISSUE THREAD

**Issue by ockam** [nystudio107/craft-scripts#36]
In case someone else has this problem, when using `sync_backups_to_s3.sh` with Laravel Forge scheduler, I needed to add `PATH` to the script so `cron` could find the aws command.
```
PATH=/home/forge/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
You can also set the command with an absolute path (`/home/forge/.local/bin/aws`), but that’s not [the recommend way](https://askubuntu.com/questions/23009/why-crontab-scripts-are-not-working).

**Comment by khalwat** [comment]
Since the cron tasks are run as the cron user, you could just add it to that account's PATH as well.
