### ISSUE TITLE
pull_db.sh on local MAMP Pro

### ISSUE THREAD

**Issue by uksitebuilder** [nystudio107/craft-scripts#43]
Any advice on getting pull_db.sh to work on local env using MAMP Pro

Here's the output I get locally when running the ./pull_db.sh script while MAMP is running

`$ ./pull_db.sh
scp: /tmp/cpuksbnet-db-dump-20181022.sql.gz: No such file or directory
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: [Warning] Using a password on the command line interface can be insecure.
*** Backed up local database to /tmp/cpuksb-db-backup-20181022.sql.gz
gunzip: can't stat: /tmp/cpuksbnet-db-dump-20181022.sql.gz (/tmp/cpuksbnet-db-dump-20181022.sql.gz.gz): No such file or directory
mysql: [Warning] Using a password on the command line interface can be insecure.
*** Restored local database from /tmp/cpuksbnet-db-dump-20181022.sql.gz`

**Comment by khalwat** [comment]
Sounds like you don't have your paths right to the actual `mysql` and `mysqldump` that Craft is using via MAMP. This article has some helpful info: https://craftcms.com/guides/database-backups-in-craft-3-with-mamp
