### ISSUE TITLE
ENV Paths Question

### ISSUE THREAD

**Issue by kgrote** [nystudio107/craft-scripts#45]
Just want to make sure I'm inputting the settings in my `.env.sh` file correctly to use the `set_perms.sh` script. So my file structure looks like this:

```
/my/server/path/craft
/my/server/path/public
/my/server/path/public/assets
```

So in the `env` file I would have these settings:

````
GLOBAL_CRAFT_PATH="./craft/"

LOCAL_ROOT_PATH="/my/server/path/"
LOCAL_ASSETS_PATH=${LOCAL_ROOT_PATH}"public/assets"
````

Is that correct? I wasn't sure because I don't see the `GLOBAL_CRAFT_PATH` variable used in the `set_perms.sh` file so I don't know if it will update permissions on just my craft files or on everything in my root directory.

**Comment by khalwat** [comment]
Yep, you've got it correct!
