### ISSUE TITLE
pull assets ownership issue

### ISSUE THREAD

**Issue by joomkit** [nystudio107/craft-scripts#46]
I have production on same server, different domain /account from staging
When I log into staging SSH and pull assets, i get all the production assets pulled down to my staging site. Great.
But the weird thing is that although i have specified in env.sh the chown group as the staging account owner, the assets folder always end up after pulling the assets with the assets folder being CHOWN'd to the production account owner.

I can't see set_perm.sh is involved in this. And i have scripts running in multiple other projects inthe same way.

ANy ideas why staging assets are being chown'd with production name after pull_assets.sh is run?

**Comment by khalwat** [comment]
It's going to be owned by whomever you are logged in as when you do the pull.
