### ISSUE TITLE
Commerce Orders & Customers

### ISSUE THREAD

**Issue by keyurshah** [nystudio107/craft-scripts#47]
Wondering what your thoughts are to exclude certain sensitive fields from being imported or obfuscate the data.

I saw in an earlier issue that you prefer to have the whole database locally, does this apply to orders and customers as well?

Thanks!

**Comment by khalwat** [comment]
So sure, if there is sensitive data that you're not in a position to handle in a secure manner, it'd make sense to not pull it down locally.
