### ISSUE TITLE
Feature Request: Multiple remotes

### ISSUE THREAD

**Issue by KatieMFritz** [nystudio107/craft-scripts#49]
For sites that have more than two environments (local/dev/staging/prod), it would be cool to be able to run pull_db or pull_assets from any environment. Currently I'm doing a two step process, where I ssh into dev to pull from staging, then pull from dev to local.

I might set this up eventually - I'll do a PR if I do. 🙂

**Comment by khalwat** [comment]
I'm not a big fan of the idea because I think it's pretty easy to make a mistake and pull down the wrong thing.

I think the right solution to this is likely wrapping a GUI around the whole thing, and making it a more user-friendly CP page or such.

**Comment by KatieMFritz** [comment]
A GUI would be amazing.

**Comment by khalwat** [comment]
While I might eventually do some kind of GUI, I don't think I'll be doing multiple remotes via the CLI so closing it down.
