### ISSUE TITLE
How does this work with Craft 3.1 project config?

### ISSUE THREAD

**Issue by parkerpearson** [nystudio107/craft-scripts#50]
I'm mainly wondering about the scenario where I am using the project.yaml to sync settings/structures between environments but then I use pull_db.sh to sync the actual db content.

Does pull_db.sh only bring in the actual content, or will it also override the db settings that are initially created from the project.yaml file?

Thanks!

**Comment by khalwat** [comment]
It will pull the entire db down, including any changes from the project.yaml -- I use them on several sites with Project Config enabled, and they work great together!
