### ISSUE TITLE
X files to consider *** Synced assets ... but nothing seems to have been pulled synced

### ISSUE THREAD

**Issue by tonyclemmey** [nystudio107/craft-scripts#52]
X files to consider *** Synced assets ... but nothing seems to have been pulled synced
```
Operating System: Debian GNU/Linux 9
Kernel: Linux 4.9.0-11-amd64
Architecture: x86-64
```

**Comment by khalwat** [comment]
I'm afraid I'm going to need a whole lot more to go on. Can you give me the complete log of the run, for example?
