### ISSUE TITLE
Skip tables on pull_db

### ISSUE THREAD

**Issue by yingban** [nystudio107/craft-scripts#54]
Hi,

I would like to know if it is possible to skip some tables on pull_db command ? 

Indeed I have a warning which I may be able to solve.
`mysqldump: Couldn’t execute ‘SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, ‘$.“number-of-buckets-specified”’)                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = ‘db_name’ AND TABLE_NAME = ‘ct_assetindexdata’;’: Unknown table ‘column_statistics’ in information_schema (1109)
mysqldump: [Warning] Using a password on the command line interface can be insecure.
mysqldump: Couldn’t execute ‘SELECT COLUMN_NAME,                       JSON_EXTRACT(HISTOGRAM, ‘$.“number-of-buckets-specified”’)                FROM information_schema.COLUMN_STATISTICS                WHERE SCHEMA_NAME = ‘db_name’ AND TABLE_NAME = ‘ct_assets’;’: Unknown table ‘column_statistics’ in information_schema (1109)`

Thanks !

**Comment by khalwat** [comment]
This is happening because you're using a MySQL 8 client with a MySQL 5.7 db. I'd sync up the versions.
