### ISSUE TITLE
mysql commands on a nitro environment

### ISSUE THREAD

**Issue by nordentwickler** [nystudio107/craft-scripts#55]
hello,

i just switched from using laradock and docker to nitro on my local dev environment. Now i'm wondering what i need to set in the config for:

```
LOCAL_MYSQL_CMD="mysql"
LOCAL_MYSQLDUMP_CMD="mysqldump"
```

On my previous environment i needed to config it like this:

```
LOCAL_MYSQL_CMD="docker exec -i laradock_mysql_1 mysql"
LOCAL_MYSQLDUMP_CMD="docker exec laradock_mysql_1 mysqldump"
```

Do we need to ssh into nitro to use the mysql there? Does anybody got it working with nitro and multipass and has got some hints for me?

greetings
Marten

**Comment by ryguy2407** [comment]
I ssh into nitro and make sure column-statistics is set to 0 in 

LOCAL_MYSQLDUMP_CMD="mysqldump --column-statistics=0"

Then it works well for me.

Hope this helps.

**Comment by khalwat** [comment]
Yep that should work!
