### ISSUE TITLE
Permission set with set_perms.sh on ./craft being 644

### ISSUE THREAD

**Issue by jayhlee** [nystudio107/craft-scripts#61]
### Question
`set_perms.sh` sets the Craft script (`./craft`) to 644, which ends up preventing any Composer Scripts that use Craft scripts from being executed. I know that changing the Craft script to have executable permissions will resolve this (`chmod a+x craft`), but I was wondering if setting the Craft script to 644 was intentional. 

Without the Craft script being executable (specifically in the production environment), Craft scripts like clear-caches and migrating—which are part of the `post-craft-update` commands—won't work. So I'm figuring the 644 permission being set on the Craft script is not intentional? Not sure, but figured I'd ask the wizard directly. Thanks!

**Comment by khalwat** [comment]
So the `craft` file is actually PHP code... and the best cross-platform way to run it is:

```
php craft xxx
```

...and this does _not_ require that the executable bit is set on the file, since it is run through `php`.
