### ISSUE TITLE
No assets being pulled

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-scripts#62]
Ive been using these scripts for years and enjoying them.
Just recently I've been getting issues syncing assets like below. There are files to consider but nothing comes across.
Ive read about some rsync issues on mac (in this case M1 silicon). Ive checked permissions, enabled disk access but all i get is below.

Is there a cache of rsync that its comparing to and deciding nothing is required? Is there an internal reference for craft that is being read/misread?

Ive tried removing my local assets directory to 'force' syncing to no avail.
Any pointers welcome:)

domain@MacBook-Pro-2 scripts % bash pull_assets.sh
Ensuring asset directory exists at '/Users/domain/sites/mycraftsite/public_html/assets/'
receiving file list ... 
1326 files to consider

**Comment by khalwat** [comment]
Well, I don't know -- but if the same script works on one computer, but not another... it's likely either an environmental setting somewhere or as you mentioned in the post, potentially an issue with rsync

It's unlikely to be something specific to the script itself, which is just bash

**Comment by alanski66** [comment]
Addendum bash set_perms.sh solved this :)
