### ISSUE TITLE
Issue with pull_db.sh

### ISSUE THREAD

**Issue by nathansnelgrove** [nystudio107/craft-scripts#63]
### Describe the bug
When I run pull_db.sh, the script correctly makes a local backup of my script, and then does nothing with the remote DB pull. It just silently fails, but never ends. It's mystifying because I can pull the same DB to my local macOS installation with no problems, but it fails on the production server.

### Versions
- Plugin version: Whatever the most recent 2021 version was
- Craft version: Craft Pro 3.7.37
- MariaDB 10.6 on production
- MySQL 5.7 remote
- PHP 8.0 on production
- PHP 7.3

One might think that this could be related to a MySQL oddity with 5.7, but I can reproduce with recent versions of MariaDB and the same versions of PHP as well.

What logs should I look at to determine what is failing and why?

**Comment by khalwat** [comment]
I'd try the commands that the script is doing by hand, to see what is failing. Probably it can't connect to the remote server or db or the like.
