### ISSUE TITLE
Automatically delete tables that are not in use

### ISSUE THREAD

**Issue by martinhellwagner** [nystudio107/craft-scripts#65]
### Question
I was wondering if it's possible to use a parameter that deletes the whole local database before a pull from the remote database, or a check that clears up any "unused" tables that are not in the remote database. The reasoning behind this is that sometimes during updates, running migrations create new tables, but when these migrations fail, those tables aren't deleted. On a new run of the pull database sync script, those tables are not automatically deleted and will therefore stay in the database as useless tables.

**Comment by khalwat** [comment]
You could add that if you want to.

Some db dumps with have those commands built into them -- remember that db dumps are just SQL commands. 

https://stackoverflow.com/questions/3476765/mysql-drop-all-tables-ignoring-foreign-keys

**Comment by martinhellwagner** [comment]
@khalwat

Thanks for the clarification! I think in this case, we will use a conditionally triggered pipeline action to drop the database before the sync script is executed.
