### ISSUE TITLE
Compatibility with CraftCMS 4

### ISSUE THREAD

**Issue by mgambella** [nystudio107/craft-scripts#67]
### Question
I noticed that the repository only mentions CraftCMS 3 in its scripts and documentation, and the last commit was made years ago. Can you please clarify the following:

- Are the scripts still actively maintained?
- Is it safe to use them in a CraftCMS 4 project?
- Are they still considered a recommended best practice for the tasks they were designed for?

**Comment by khalwat** [comment]
They are not actively maintained, but only in the sense that I'm not aware of any issues with them (other than potential features people want added).

Yes, they should work fine for Craft 4

Yes, if you need to pull db's down to your local environment, they are still a viable way to do it.
